server:
  port: 8765
  
eureka:
  client:
    service-url:
     defaultZone: http://ec2-54-197-79-102.compute-1.amazonaws.com:8761/eureka
      
spring:
  application:
    name: api-gateway
  cloud:
   gateway:
     discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
     default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
     globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: 
              - POST
              - GET
              - DELETE
              - PUT
              - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true         
          
          
          
          
     routes:     
     - id: cambio-service
       uri: lb://cambio-service
       predicates: 
       - Path=/cambio-service/**
#
     - id: book-service
       uri: lb://book-service
       predicates:
       - Path=/book-service/**
#
     - id: book-crud
       uri: lb://book-crud
       predicates: 
       - Path=/book-crud/**
#
     - id: openapi
       uri: lb://api-gateway
       predicates: 
       - Path=/v3/api-docs/**
#
       filters:
       - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs