server:
  port: 8889

spring:
  application:
    name: erudio-config-server
#  profiles:
 #   active:
  #    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elisio-ricardo/erudio-config-server
          default-label: main
          search-paths:
            - 'greeting-service*'