<<<<<<< HEAD

server:
  port: 7000

topic:
  name: test2
  
eureka:
  client:
    service-url:
     defaultZone: http://ec2-54-197-79-102.compute-1.amazonaws.com:8761/eureka
spring:
  application:
    name: book-crud

  kafka:
    consumer:
      group-id: worker
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: br.com.erudio.dtos.MessageConsumerDTO
    bootstrap-servers: ec2-3-86-85-184.compute-1.amazonaws.com:9091

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-83-249-155.compute-1.amazonaws.com:3336/book_crud?createDatabaseIfNotExist=True&useTimezone=true&serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://ec2-3-83-249-155.compute-1.amazonaws.com:3336/
    schemas: book_crud
    user: root
    password: 
    
springdoc:
  api-docs:
    path: book_crud/v3/api-docs
=======
spring:
  profiles:
    active: local
>>>>>>> ec399fea87443fd7cc2a00b156383b3510b990f5
